---
- name: Ensure git is installed
  ansible.builtin.apt:
    pkg: git
    cache_valid_time: 86400 # 1 day

# etckeeper will fail when invoked by cron if this is not already set. see
# https://unix.stackexchange.com/a/368851
- name: Ensure git user.email is set for root
  community.general.git_config:
    name: user.email
    repo: /etc
    scope: local
    value: "{{ etckeeper_root_user_git_email }}"

- name: Install etckeeper package
  ansible.builtin.apt:
    pkg: etckeeper
    cache_valid_time: 86400 # 1 day

# NB: just apt-installing the etckeeper apt package will automatically set up
# etckeeper to watch /etc, so if that's not already happening, that will happen
# in addition to setting up tracking for the custom target dir specified here
- name: "Check if etckeeper already set up to watch {{ etckeeper_target_dir }}"
  ansible.builtin.stat:
    path: "{{ etckeeper_target_dir }}/.etckeeper"
  register: etckeeper_installation

- name: "Gitignore unnecessary files"
  ansible.builtin.blockinfile:
    path: "{{ etckeeper_target_dir }}/.gitignore"
    block: "{{ etckeeper_gitignore_additions }}"
    mode: 'u=rw,go=r'
    create: true
  when: etckeeper_gitignore_additions

- name: Set up weekly git garbage collection
  ansible.builtin.template:
    src: etckeeper_git_gc.j2
    dest: /etc/cron.weekly/etckeeper_{{ etckeeper_task_codename }}_git_gc
    mode: 'u=rwx,go=r'

- name: Perform custom actions when not operating on default /etc dir
  when: etckeeper_target_dir != "/etc"
  block:
    - name: "Ensure target existent dir {{ etckeeper_target_dir }}"
      ansible.builtin.file:
        path: "{{ etckeeper_target_dir }}"
        state: directory
        mode: 'u=rwx,go=rx'

    - name: "Set up etckeeper to watch {{ etckeeper_target_dir }}"
      ansible.builtin.command: "etckeeper init -d {{ etckeeper_target_dir }}"
      args:
        creates: "{{ etckeeper_target_dir }}/.git"

    - name: "Add cron job for autocommit {{ etckeeper_task_codename }}"
      ansible.builtin.template:
        src: etckeeper_autocommit.j2
        dest: /etc/cron.daily/etckeeper_{{ etckeeper_task_codename }}_autocommit
        mode: 'u=rw,go=r'

    - name: "Run daily cron job immediately after installation in {{ etckeeper_target_dir }}"
      ansible.builtin.command: "/etc/cron.daily/etckeeper_{{ etckeeper_task_codename }}_autocommit"
      changed_when: false
      when: not etckeeper_installation.stat.exists
